### ISSUE TITLE
python run_crslab.py --config config/crs/kgsf/tgredial.yaml

### ISSUE THREAD

**Issue by lling-2021** [RUCAIBox/CRSLab#40]
Traceback (most recent call last):
  File "run_crslab.py", line 47, in <module>
    run_crslab(config, args.save_data, args.restore_data, args.save_system, args.restore_system, args.interact,
  File "/home/**/project/crs/CRSLab/crslab/quick_start/quick_start.py", line 73, in run_crslab
    CRS.fit()
  File "/home/**/project/crs/CRSLab/crslab/system/kgsf.py", line 186, in fit
    self.train_recommender()
  File "/home/**/project/crs/CRSLab/crslab/system/kgsf.py", line 144, in train_recommender
    metric = self.evaluator.rec_metrics['hit@1'] + self.evaluator.rec_metrics['hit@50']
  File "/home/**/project/crs/CRSLab/crslab/evaluator/metrics/base.py", line 214, in __getitem__
    return self.get(item)
  File "/home/**/project/crs/CRSLab/crslab/evaluator/metrics/base.py", line 211, in get
    raise
RuntimeError: No active exception to reraise

**Comment by nageswarib** [comment]
Hi, I'm getting the same error message when running tgredial.py. The dataset and metrics are being set to empty and raising this errror. Please advise.

**Comment by txy77** [comment]
Thank you for your feedback. I've fixed the bug now, you can try again.
