### ISSUE TITLE
AssertionError: [ Checksum for redial_nltk.zip

### ISSUE THREAD

**Issue by ifty1987** [RUCAIBox/CRSLab#45]
when i run this " !sh script/redial/train/redial_rec_train.sh" on anaconda i got this error. same error is coming when executing on goole colab. please help anyone

frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
2022-06-10 11:08:18.617 | INFO     | crslab.config.config:__init__:80 - [CONFIG] C2CRS_Model, C2CRS_Model
2022-06-10 11:08:18.633 | INFO     | crslab.config.config:build_path:137 - save_path = C:\Users\91790\c2crs\save\ReDial_C2CRS_Model2022-06-10-11-08-18
2022-06-10 11:08:18.633 | INFO     | crslab.config.config:build_path:144 - restore_path = C:\Users\91790\c2crs\save\ReDial_C2CRS_ModelNone
Downloading redial_nltk.zip: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "run_crslab.py", line 79, in <module>
    run_crslab(config, args.save_data, args.restore_data, args.save_system, args.restore_system, args.interact,
  File "C:\Users\91790\c2crs\crslab\quick_start\quick_start.py", line 57, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "C:\Users\91790\c2crs\crslab\data\__init__.py", line 52, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "C:\Users\91790\c2crs\crslab\data\dataset\redial\redial.py", line 83, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "C:\Users\91790\c2crs\crslab\data\dataset\base.py", line 44, in __init__
    build(dpath, dfile, version=resource['version'])
  File "C:\Users\91790\c2crs\crslab\download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "C:\Users\91790\c2crs\crslab\download.py", line 77, in download_file
    self.checksum(dpath)
  File "C:\Users\91790\c2crs\crslab\download.py", line 63, in checksum
    raise AssertionError(
AssertionError: [ Checksum for redial_nltk.zip from 
http://d0.ananas.chaoxing.com/download/417f6ac16282e4910fc93973e954ab42?fn=nltk
does not match the expected checksum. Please try again. ]

**Comment by txy77** [comment]
Try baidu or google? There are so many good tutorials, you can find the one that suits you best.

**Comment by wxl1999** [comment]
@ifty1987 Sorry for late reply, we have updated the download link used in the package, please update.
