### ISSUE TITLE
cpu环境报错：libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by longshuicui** [RUCAIBox/CRSLab#6]
(crslab) ubuntu@ip-10-0-1-244:~/cls/CRSLab$ python run_crslab.py --config config/crs/kgsf/redial.yaml 
Traceback (most recent call last):
  File "run_crslab.py", line 13, in <module>
    from crslab import run_crslab
  File "/home/ubuntu/cls/CRSLab/crslab/__init__.py", line 5, in <module>
    from crslab.system import get_system
  File "/home/ubuntu/cls/CRSLab/crslab/system/__init__.py", line 12, in <module>
    from .kbrd import KBRDSystem
  File "/home/ubuntu/cls/CRSLab/crslab/system/kbrd.py", line 16, in <module>
    from crslab.system.base import BaseSystem
  File "/home/ubuntu/cls/CRSLab/crslab/system/base.py", line 19, in <module>
    from transformers import AdamW, Adafactor
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/__init__.py", line 34, in <module>
    from . import dependency_versions_check
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/dependency_versions_check.py", line 34, in <module>
    from .file_utils import is_tokenizers_available
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/transformers/file_utils.py", line 231, in <module>
    import torch_scatter
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/ubuntu/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory

**Comment by Lancelot39** [comment]
Thanks for your feedback. This issue is caused by our toolkit utilizing the GPU (if validated) in default. We will try to set the environment in command line in the future version, in which you can use GPU/CPU as you like.

Here, we give out a simple approach for you to run our toolkit in CPU by the following code:
`CUDA_VISIBLE_DEVICES=-1 python run_crslab.py --config config/crs/kgsf/redial.yaml`

**Comment by wxl1999** [comment]
We have added `gpu` argument in `run_crslab.py`, which specifies GPU id(s) to use(only supports using a single GPU now) and it defaults to use cpu.

So now you only need to run our toolkit in CPU by the following code:
`python run_crslab.py --config config/crs/kgsf/redial.yaml`
