### ISSUE TITLE
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LQlq123** [RUCAIBox/CRSLab#68]
(d2l) tislab20@tislab20-Precision-7920-Tower:~/Desktop/lq/CRSLab-main$ CUDA_VISIBLE_DEVICES=-1 python run_crslab.py --config config/crs/kgsf/redial.yaml
2023-02-24 03:34:20.942 | INFO     | crslab.config.config:__init__:79 - [Dataset: ReDial tokenized in nltk]
2023-02-24 03:34:20.942 | INFO     | crslab.config.config:__init__:81 - [Model: KGSF]
2023-02-24 03:34:20.942 | INFO     | crslab.config.config:__init__:88 - [Config]
{
    "dataset": "ReDial",
    "tokenize": "nltk",
    "embedding": "word2vec.npy",
    "context_truncate": 256,
    "response_truncate": 30,
    "scale": 1,
    "model": "KGSF",
    "token_emb_dim": 300,
    "kg_emb_dim": 128,
    "num_bases": 8,
    "n_heads": 2,
    "n_layers": 2,
    "ffn_size": 300,
    "dropout": 0.1,
    "attention_dropout": 0.0,
    "relu_dropout": 0.1,
    "learn_positional_embeddings": false,
    "embeddings_scale": true,
    "reduction": false,
    "n_positions": 1024,
    "pretrain": {
        "epoch": 3,
        "batch_size": 128,
        "optimizer": {
            "name": "Adam",
            "lr": 0.001
        }
    },
    "rec": {
        "epoch": 9,
        "batch_size": 128,
        "optimizer": {
            "name": "Adam",
            "lr": 0.001
        }
    },
    "conv": {
        "epoch": 90,
        "batch_size": 128,
        "optimizer": {
            "name": "Adam",
            "lr": 0.001
        },
        "lr_scheduler": {
            "name": "ReduceLROnPlateau",
            "patience": 3,
            "factor": 0.5
        },
        "gradient_clip": 0.1
    },
    "gpu": [
        -1
    ],
    "model_name": "KGSF"
}
Traceback (most recent call last):
  File "run_crslab.py", line 41, in <module>
    from crslab.quick_start import run_crslab
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/quick_start/__init__.py", line 1, in <module>
    from .quick_start import run_crslab
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/quick_start/quick_start.py", line 13, in <module>
    from crslab.system import get_system
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/system/__init__.py", line 18, in <module>
    from .inspired import InspiredSystem
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/system/inspired.py", line 12, in <module>
    from crslab.system.base import BaseSystem
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/system/base.py", line 30, in <module>
    from crslab.model import get_model
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/model/__init__.py", line 18, in <module>
    from .crs import *
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/model/crs/__init__.py", line 2, in <module>
    from .kbrd import *
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/model/crs/kbrd/__init__.py", line 1, in <module>
    from .kbrd import KBRDModel
  File "/home/tislab20/Desktop/lq/CRSLab-main/crslab/model/crs/kbrd/kbrd.py", line 26, in <module>
    from torch_geometric.nn import RGCNConv
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_sparse/__init__.py", line 34, in <module>
    from .storage import SparseStorage  # noqa
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_sparse/storage.py", line 5, in <module>
    from torch_scatter import segment_csr, scatter_add
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch_scatter/__init__.py", line 11, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/tislab20/anaconda3/envs/d2l/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by lengshuiyu332** [comment]
Thank you for bringing this issue to my attention. Based on the error you're experiencing, there may be some mistakes with the environment setup. I suggest checking your PyTorch version and other dependencies to ensure they are compatible with the project.

To check for PyTorch versions, you can refer to the PyTorch website and check the previous versions available at https://pytorch.org/get-started/previous-versions. Additionally, PyTorch Geometric may also be a problem, and you can find the installation instructions at https://pytorch-geometric.readthedocs.io/en/latest/install/installation.html.     

You could read the README again to check your installation.
