### ISSUE TITLE
training 设置报错

### ISSUE THREAD

**Issue by xy-derrick** [RUCAIBox/CRSLab#87]
def train_recommender(self):
        if hasattr(self.rec_model, 'bert'):
            if os.environ["CUDA_VISIBLE_DEVICES"] == '-1':
                bert_param = list(self.rec_model.bert.named_parameters())
            else:
                bert_param = list(self.rec_model.module.bert.named_parameters())
            bert_param_name = ['bert.' + n for n, p in bert_param]
        else:
            bert_param = []

在这段代码中  bert_param = list(self.rec_model.module.bert.named_parameters()) 报错说 'TGRecModel' object has no attribute 'module'，请问原因是？然后想问一下这个module是干嘛的

**Comment by xy-derrick** [comment]
问这个是因为在使用interact的时候确实能获得推荐结果但是response部分是空的

**Comment by ChenCyril** [comment]
我也有点奇怪...用GPU跑就报这个错，CPU跑倒是没问题emmm...

**Comment by enchantee00** [comment]
change
`bert_param = list(self.rec_model.module.bert.named_parameters())`
to
`bert_param = list(self.rec_model.bert.named_parameters())`

Can fix this error

**Comment by nguyenminhduc392002** [comment]
"Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/nltk/util.py", line 468, in ngrams
    history.append(next(sequence))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/kaggle/working/CRSLab-main/run_crslab.py", line 43, in <module>
    run_crslab(config, args.save_data, args.restore_data, args.save_system, args.restore_system, args.interact,
  File "/kaggle/working/CRSLab-main/crslab/quick_start/quick_start.py", line 73, in run_crslab
    CRS.fit()
  File "/kaggle/working/CRSLab-main/crslab/system/inspired.py", line 206, in fit
    self.train_conversation()
  File "/kaggle/working/CRSLab-main/crslab/system/inspired.py", line 188, in train_conversation
    self.step((batch), stage='conv', mode='val')
  File "/kaggle/working/CRSLab-main/crslab/system/inspired.py", line 120, in step
    self.conv_evaluate(pred, batch[-1])
  File "/kaggle/working/CRSLab-main/crslab/system/inspired.py", line 89, in conv_evaluate
    self.evaluator.gen_evaluate(p_str, [r_str])
  File "/kaggle/working/CRSLab-main/crslab/evaluator/standard.py", line 80, in gen_evaluate
    for token in ngrams(hyp, k):
RuntimeError: generator raised StopIteration" Can you help me fix this error?
